### ISSUE TITLE
Cannot open the file ../mnist/train-images-idx3-ubyte

### ISSUE THREAD

**Issue by AlexHoffman9** [stonezwr/ST-RSBP#1]
I got the following error when running ./build/CUDA-RSNN and using the MNIST dataset:
```
Cannot open the file: ../mnist/train-images-idx3-ubyte
CUDA-RSNN: /home/vortex/ahoffman/comp551/ST-RSBP/readData/readMnistData.cpp:174: void readMnistImg(const string&, std::vector<cuMatrix<float>*, std::allocator<cuMatrix<float>*> >&, int): Assertion `0' failed.
```
I already ran the get_mnist script and I see the train-images-idx3-ubyte file in the mnist directory, so I am unsure why the code can't open it

**Comment by jverecken** [comment]
I managed to get around this error by doing 
```
cd build
./CUDA-RSNN
```
But therefore it means there is a mismatch with what the documentation tells.

Edit : 
To avoid segmentation fault afterwards, it is better remove ``../`` in the path of the configuration text file.

**Comment by stonezwr** [comment]
The path of the dataset is set in the Config folder. By default, I suppose the mnist folder is in ../ 
You can either change the data path in the config file or move the mnist to the ../

**Comment by AlexHoffman9** [comment]
Replacing `../mnist...` with `./mnist...` in the config file worked for me
